include:
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml"
  - "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml"

build-pypi-package:
  stage: build
  image: python:3.7
  script:
    - pip install jupyter-packaging
    - python setup.py check sdist bdist_wheel
  artifacts:
    expire_in: 1 day
    paths:
      - dist/